<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB1McO4P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB1McO4P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB1McO4P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB1McO4P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB1McO4P\App_KernelDevDebugContainer([
    'container.build_hash' => 'B1McO4P',
    'container.build_id' => '4c9785a3',
    'container.build_time' => 1743869751,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB1McO4P');
