<?php

namespace ContainerB1McO4P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PCzPUCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PCzP_uC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PCzP_uC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'destinationRepository' => ['privates', 'App\\Repository\\DestinationRepository', 'getDestinationRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'destinationRepository' => 'App\\Repository\\DestinationRepository',
            'manager' => '?',
        ]);
    }
}
