<?php

namespace ContainerB1McO4P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gd1VmCBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gd1VmCB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gd1VmCB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'partenaireRepository' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService', true],
        ], [
            'managerRegistry' => '?',
            'partenaireRepository' => 'App\\Repository\\PartenaireRepository',
        ]);
    }
}
