parameters:
  uploads_directory: '%kernel.project_dir%/public/uploads'
  profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
  logos_directory: '%kernel.project_dir%/public/uploads/logos'
  part_directory: '%kernel.project_dir%/public/uploads/partenaires'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $uploadsDirectory: '%uploads_directory%'
      $profilePicturesDirectory: '%profile_pictures_directory%'
      $logosDirectory: '%logos_directory%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\EventListener\LoginSuccessListener:
    tags:
      - { name: kernel.event_listener, event: security.authentication.success, method: onLoginSuccess }

  App\EventListener\LogoutSuccessListener:
    tags:
      - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent, method: onLogoutSuccess }

  # AppExtension for Twig globals
  App\Twig\AppExtension:
    tags: [ 'twig.extension' ]
