<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNuGyiV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNuGyiV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCNuGyiV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNuGyiV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCNuGyiV\App_KernelDevDebugContainer([
    'container.build_hash' => 'CNuGyiV',
    'container.build_id' => '8fb7c87d',
    'container.build_time' => 1743124581,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNuGyiV');
